### ISSUE TITLE
allow files in .bazelproject to show

### ISSUE THREAD

**Issue by rverma-nikiai** [bazelbuild/intellij#1109]
While the directory session is awesome if we don't provide '.' as directories, it stops showing us any files in root.  In addition to that if we have already added '.' in directories, we are missing a way to add other sub dir as modules.

<img width="368" alt="Screenshot 2019-08-23 at 12 17 37 PM" src="https://user-images.githubusercontent.com/38323616/63572250-0de40f80-c5a0-11e9-9440-ba371d5f7036.png">

It would be nice if it can still show all files in the root dir, or we can specify which files to see as well.

Another issue with the same behavior is, if we didn't add a module in directories or remove with '-' , intellij still indexes that directory and show files from that as well. On sync can we drop the index for those directories. 

<img width="1203" alt="Screenshot 2019-08-23 at 12 15 12 PM" src="https://user-images.githubusercontent.com/38323616/63572482-995da080-c5a0-11e9-8311-62f3684a28d0.png">

**Comment by rverma-nikiai** [comment]
Also wondering why '.ijwb' is highlighted as a module by default when using the directory as '.', and we can make any other dir as a module.

**Comment by chaoren** [comment]
We include the project data directory as a module so you can search for and edit your .bazelproject file.

**Comment by rverma-nikiai** [comment]
That makes sense, but it's appearing as the only module, can we enforce other directories as a module if we add '.' in directories. It's not affecting any functionalities, I guess we are so used to it while using Maven/Gradle.

**Comment by rverma-nikiai** [comment]
That would be a hurdle in auto module generation, but whats about if someone want to declare a sub dir as a module. I believe we should have this flexibility. This might be helpful with unnecessary classpath leak as well.

**Comment by ittaiz** [comment]
I think there are two separate requests here. Allowing selection of files from the root directory to show up and multi-module IJ project. @rverma-nikiai any chance we can split the latter to a different issue?
We, at Wix, are also very interested in showing the files of the root directory without selecting `.` in the directories. This is because we tell people to import sub sections of the workspace but there's no way to see all kinds of files (bzls and others) from the root that way.
@liucijus even [patched](https://github.com/wix-playground/intellij/commit/7dc020e7e4221f22ac24e19df86d6cb5192106c7) it in our fork. 
@chaoren Any chance you'll be willing to take this (or a variation of this) as a contribution?

**Comment by chaoren** [comment]
Is it not the same as including the root and then excluding the subdirectories via the .bazelproject file?
Is the problem that you have too many directories in the root?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
