### ISSUE TITLE
Bazel binary path (sometimes?) gets reset after version upgrade

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1131]
Hi,
Developers internally report that after they upgrade a plugin version their build doesn't work because the binary path gets reset to `bazel` instead of `/usr/local/bin/bazel`.
I took a look in [BlazeUserSettings.java](https://github.com/bazelbuild/intellij/blob/a78ec3e4be36427c31e7eee81dc097b6d85cd155/base/src/com/google/idea/blaze/base/settings/BlazeUserSettings.java#L61) and saw that for `blaze` you have a better default than `bazel`.
Can we have the same default for `bazel` binary path? I can send the PR if needed

**Comment by brendandouglas** [comment]
For blaze we know exactly where the binary will be, because we only have to worry about internal corp machines and development environments. For bazel, it's up to the user where they install it. We came to the conclusion that 'bazel' covers more use cases than '/usr/local/bin/bazel', and is relatively intuitive. Happy to reconsider if that's not actually the case.

That said, it shouldn't be getting reset unless you're somehow wiping the user settings along with updating the plugin -- the base plugin itself won't be doing that.

**Comment by jin** [comment]
Using Bazel from the path is a better default. Some systems have `/usr/bin/bazel`, `/usr/local/bin/bazel`, and it works very differently on Windows and NixOS / nixpkgs-based systems. 

I also haven't encountered a settings reset for the PATH after an upgrade.

**Comment by ittaiz** [comment]
👍 Fair enough. I'll try to see if it's something we do that messes up the bazel binary path on upgrade. Thanks!
