### ISSUE TITLE
Detect and setup IntelliJ modules & dependencies.

### ISSUE THREAD

**Issue by daicoden** [bazelbuild/intellij#115]
There seems to be only two modules created when importing bazel projects. `.project-data-dir` and `.workspace`.

For large projects this is a problem because every single class is available for discovery, even though the class may be in distant areas, and there is no bazel configuration to link the two. 

Could we use package_groups and a heuristic that if a a package_group contains a package which is a parent directory, we group it into an intelliJ module? This process also sets up the dependencies between modules.

I'm still new to bazel, but have used pants. I'm trying to wrap my head around how development is supposed to feel, so perhaps there's a different way to have isolation in the IDE based on the bazel configuration? I've tried playing around with project views, but there would need to be a tool to generate new project views based on a target when switching tasks. Other ideas?

**Comment by brendandouglas** [comment]
There's a fundamental mismatch between the units of compilation in IntelliJ (directories) and Bazel (targets).

Simply mapping Bazel packages to IntelliJ modules doesn't work, because:
1. there are cyclic dependencies between packages
2. IntelliJ has O(n^2) performance with the number of modules

The Bazel plugin originally did this, and we spent 2-3 quarters trying to fix all the O(n^2) bugs in IntelliJ, but eventually gave up and moved to the current single-module system (with an additional project directory module).

What actual problems are being caused by having every class available for discovery?

Generally, we handle such issues by having separate projects for disjoint parts of the code base.

**Comment by daicoden** [comment]
The O(n^2) is a bummer, pants handles this by generating modules with some heuristic which are included in the specified target. Pretty cool you tried to fix the root cause.

hmmm, I guess what spurred me to open the issue is that it feels like I'm not getting a lot of help from IntelliJ.  Following the recommended 1 BUILD file per package is cumbersome, and hard to keep consistent.

I was expecting the intelliJ plugin to help guide best practice by lightening the burden of maintaining the bulid files. For instance, I was expecting java_library, srcs, and package_group to be auto-managed. When importing a new class, the dependency would be automatically added to the build deps if relying on classes within the same package_group (or same visibility level). When refactoring and moving files, deps updated. etc.

I realize bazel is much more flexible, and there would be lots of cases where it's not appropriate to auto-manage the build files. But for the basic feature development I was hoping for more convention tooling.

I'm still getting used to it, so maybe the plugin is doing all it can without restricting bazel features.

**Comment by brendandouglas** [comment]
I'd take the 'one BUILD file per Java package' recommendations with a grain of salt. As you say, it results in a lot of extra maintenance burden (and the additional jars also worsen performance in some cases).

Have a look at the structure of this project for a possible alternative.
