### ISSUE TITLE
Invalid package name when running under Windows

### ISSUE THREAD

**Issue by lunivore** [bazelbuild/intellij#1186]
With this .bazelproject file:
```
directories:
  .
  src/main

test_sources:
  src/test
  src/scenarios

targets:
  //:myapp
  //src/main:myapp_lib
  //src/tests:myapp_tests
  //src/scenarios:myapp_scenarios

additional_languages:
  kotlin
```

I get an error starting:

`ERROR: Skipping '//src\main:all': Invalid package name 'src\main': package names may contain A-Z, a-z, 0-9`

I suspect it's a Windows problem just because of the way the / has been switched round to \\. Posted here by request from @jin following [my StackOverflow question](https://stackoverflow.com/questions/58066347/invalid-package-name-when-running-bazel-under-windows-in-intellij).

IntelliJ version 2019.2.2
Bazel plugin version 2019.08.19.0.6

**Comment by KrauseStefan** [comment]
I had a similar issue currently using this workaround to get partial import to work.
https://github.com/KrauseStefan/intellij/commit/d37b740998dd8f85cb6455b7031ac38cfc4c2153

I don't know if this solution works in general.

The issue is that the path is used directly on Linux but on windows `\` needs to be converted to `/`, I don't know if `\` is allowed in a target path by bazel else I think this would be an approach.
``` java
return new TargetExpression("//" + localPackage.relativePath() + ":all");
```
``` java
return new TargetExpression("//" + localPackage.relativePath().replace("\\", "/") + ":all");
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
