### ISSUE TITLE
Enhance move class refactoring to also contribute BUILD file changes

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#120]
This is following a discussion with @chaoren.
Given 4 packages a/b/c/d with 4 targets in them 1/2/3/4 and given `c:3` depends on `b:2` which in turn depends on `a:1` when I move a file which belongs to `b:2` to `d:4` I'd like `d:4` to have a dependency on `a:1` and have `c:3` to also add a dependency to `d:4`.

**Comment by brendandouglas** [comment]
Given the amount of work involved in implementing this well, and how infrequently I'd expect this to be used in practice, this isn't something we're likely to pursue in the short-medium term.

Happy to reconsider if there's sufficient demand, but this isn't something we've had requests for internally. 

We could look at collecting stats on how often move class refactoring is done, and use that information to retriage this at a later date.

**Comment by chaoren** [comment]
Had a discussion with @brendandouglas. Big problem is that it's difficult to compute class level dependency. I.e., we know that `c:3` depends on `b:2`, but we don't know which source file actually requires this dependency. Likewise, we don't know which specific class in `b:2` is the dependency required by `c:3`. Computing this is possible, but would be very difficult.

**Comment by ittaiz** [comment]
Why not start with an over approximation of targets instead of classes?
Less value but much easier.
Presumably people can later utilize unused-deps to prune down.

BTW, we move files (via move and move class refactoring) all the time. Especially between different packages of the same maven module (which will now be harder since they're a different compilation unit in bazel)

**Comment by chaoren** [comment]
You mean having all dependencies of the target move with the class?

**Comment by ittaiz** [comment]
I mean copy, yes.

**Comment by brendandouglas** [comment]
From our perspective (a large, unwieldy code base, containing targets with large transitive closures), over-approximating (e.g. by simply copying over all the deps) is worse than under-approximating / doing nothing.

It's dangerous, because Bazel will silently compile the new target, and there's no trigger to clean up the unnecessary dependencies. Doing nothing means the developer is forced to add dependencies, hopefully in a thoughtful way.

If we were to do this, we'd try hard to err on the side of under-approximating (while getting as close as practical). If the target is in the project, and currently compiles, this might not be too difficult.

> which will now be harder since they're a different compilation unit in bazel

Ah, that kind of copying would happen frequently. We (the IJ plugin team) don't hit that often, because we have a small number of BUILD targets (each one covering many java packages).

Bazel does advocate the opposite approach though, so we should try to support it better -- I'll see what we can do.

**Comment by brendandouglas** [comment]
Actually, could you expand a bit on your use case?

When you move a Java class to a different package, how would the plugin know which target it should now be built by?

We could add heuristics to guess, but again we risking silently doing the wrong thing. We could also try to insert another UI step into the refactoring process.

**Comment by ittaiz** [comment]
I agree that over approximation is probably incorrect for the vast use-cases a tool like Bazel tries to solve (scale etc.).
We try to follow the 1:1:1 which simplifies many things this being one of them.
Maybe the plugin can check to see if a glob pertaining this package exists and if so associate the file with that target.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by ittaiz** [comment]
It's your call.
I can tell you that this was one of the biggest pains when moving to bazel and to be honest I think that bazel had a negative effect on the quality of our codebase in this aspect

**Comment by sgowroji** [comment]
Thanks for responding
