### ISSUE TITLE
Support CLion 2019.3

### ISSUE THREAD

**Issue by wmmc88** [bazelbuild/intellij#1354]
Any eta on clion 2019.3 Support?

**Comment by samolisov** [comment]
I get the bazel plugin for Clion 2019.3. If you need the plugin working on the latest EAP (193.5096.27 - 12.11.2019) please apply patches from PR #1381.

**Comment by samolisov** [comment]
To maintainers,

To let my PR be merged, I need to feel and discuss the changes in a related issue. I believe this issue it the best point.

In order to support Clion 2019.3, the following changes at least have to be applied to the build system (.bzl, BUILD and WORKSPACE files):

 - New dependency (Clion 2019.3) should be added to `WORKSPACE` and
`intellij_platform_sdk`. The following changes must be mirrored through the BAZEL projects: `python` is now
replaced with `python-ce` while `clion-test-google` and `clion-test-catch` are
removed from the `sdk` into their own set of plugins.

 - Since `clion-test-google` and `clion-test-catch` now are plugins, these
plugins has been added as dependencies into the `META-INF/clwb.xml`
manifest.

A minor change is proposed: to align what a user see on the Bazel Console with what will exactly be executed. I mean all escaped symbols such as `""` and `/`. It can be used (and I personally have used) during a troubleshooting session if a Bazel synchronization doesn't work. In my PR #1381 I've changed a bit the output into the console but broke down some unit tests. I think the tests can be changed if we get a consensus about how the output should work. If you think this is another topic, I'll reset the commit and we can skip this changes to be focused on Clion 2019.3.

**Comment by noxwell** [comment]
If you are tired of waiting for this issue - here is updated changes compatible to latest CLion 2019.3.2 and Bazel plugin https://github.com/noxwell/intellij/commit/127680e0eb782123053a5db1f2153720df7f31ea. To build your own version just do this:
```
git clone https://github.com/bazelbuild/intellij.git
cd intellij
git remote add noxwell https://github.com/noxwell/intellij.git
git fetch noxwell
git checkout v2019.12.16
git cherry-pick -n noxwell/clion-2019.3
bazel clean
bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-beta
```
Then you can install plugin from `bazel-bin/clwb/clwb_bazel.zip`. `v2019.12.16` is most recent stable version of Bazel plugin, but of course you can use newer version if any comes available, so you will be up-to-date.

**Comment by faisalthaheem** [comment]
@noxwell thanks, those instructions worked great. There were some checksum  mismatch errors when fetching intellij but easily fixed by updating the hash in workspace with the one shown on console.

**Comment by vinayan3** [comment]
Any updates to this or a set of things that need to get the support working?

**Comment by brendandouglas** [comment]
The latest few releases support CLion 2019.3: https://plugins.jetbrains.com/plugin/9554-bazel/versions
