### ISSUE TITLE
Go To Definition(s) doesn't work with external code.

### ISSUE THREAD

**Issue by lshamis** [bazelbuild/intellij#138]

**Comment by brendandouglas** [comment]
I'm not able to reproduce this issue -- could you add some details?

**Comment by tarobins** [comment]
I see this issue with this project.  If you open in intellij and build then go to the generated person java proto class, you can't go to it's superclass, com.google.protobuf.GeneratedMessageV3.

I think this issue is related to the one I've been trying to solve here https://groups.google.com/forum/#!topic/bazel-discuss/1SDVzn-XCqo, which I have a few temporary solutions for but returns as soon as I sync with bazel again.

**Comment by brendandouglas** [comment]
@tarobins, in your case, it's an bug specific to java_proto_library.

java_proto_library has an implicit dep on @com_google_protobuf_java//:protobuf_java, but doesn't expose that dependency either via an attribute or a skylark provider.

So there's no way for our plugin aspect to propagate to that implicit dep.

In the next build, I've worked around this by adding all jars in your project target's jdeps file to the project libraries. This means there'll be no source jars attached (because jdeps only lists the interface or class jar), but until java_proto_library correctly reports its own deps, this is all we can do.
