### ISSUE TITLE
ndk header resolve

### ISSUE THREAD

**Issue by jiqimaogou** [bazelbuild/intellij#1388]
![image](https://user-images.githubusercontent.com/1407040/68761917-12c0d880-0650-11ea-865d-13de7d1ca2ed.png)

how can I resolve ndk headers?

**Comment by jiqimaogou** [comment]
![image](https://user-images.githubusercontent.com/1407040/68993444-333c9d00-08b3-11ea-92b1-5d99bc5b2e3e.png)

android studio info.

and the c file does not belong to any project target, 

![image](https://user-images.githubusercontent.com/1407040/68993446-3df73200-08b3-11ea-91e8-1583fe691f97.png)

and i debug the plugin
![image](https://user-images.githubusercontent.com/1407040/68993454-523b2f00-08b3-11ea-8e20-e9ee0752414f.png)

the source has added to the configuration

**Comment by cpsauer** [comment]
I know this issue is old, but in case anyone else is looking at this:
Adding the following to my .bazelproject solved this (and some other issues), at least for me!
```
sync_flags:
  --cpu=arm64-v8a
  --crosstool_top=@androidndk//:default_crosstool
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
```

More of an explanation: When I was getting similar behavior, it was actually Android Studio was trying to provide C++ completion not for the NDK but for my desktop platform. These lines [manually configure the cc_libraries to be compiled for the NDK](https://docs.bazel.build/versions/master/android-ndk.html#building-a-cc_library-for-android-without-using-android_binary). For more details see the issue I'd mentioned this from, above.

**Comment by alice-ks** [comment]
Thanks for posting a solution here, Christopher! It sounds as if we can close this issue. Please re-open this issue if there's still something missing.
