### ISSUE TITLE
Option --symlink_prefix breaks IntelliJ plugin

### ISSUE THREAD

**Issue by RaresI** [bazelbuild/intellij#156]
When using any non-default argument for the --symlink_prefix option, the IntelliJ plugin will take a very long time to scan the project folder, because it will include all the sources and libraries found under the new prefix. This happens event if the new prefix is specifically excluded in Project Structure Settings.

Furthermore, the bazel-out symlink is always created by the Bazel plugin, without consideration to the --symlink_prefix present in the tools/bazel.rc file.

Steps to reproduce:
1. Add to tools/bazel.rc file
common --symlink_prefix=.bazel/

2. Open the workspace in IntellIJ, or sync it if already opened.

3. The console will  show Computing Directory Structure a very long time, or the same task will get stuck in Background Tasks.
    DirectoryStructure: 302,3s

**Comment by brendandouglas** [comment]
bazel-out (and bazel-genfiles, etc.) are created by Bazel itself, and we explicitly exclude them from indexing.

Excluding directories in the 'Project Structure' settings won't work, because those settings are overridden at each sync by the contents of your .bazelproject file.

Instead, try excluding the symlink by adding a line to your .bazelproject file (Bazel > Project > Open local project view file), for example:

directories:
  -.bazel

**Comment by brendandouglas** [comment]
Lost the whitespace in the example. It should be:
```
directories:
  -.bazel
```

**Comment by brendandouglas** [comment]
The bazel-out symlink always being created is discussed here: https://github.com/bazelbuild/bazel/issues/3796

**Comment by RaresI** [comment]
Thank you for answering! I have already tried the excludes in project view file, both:
directories:
  -.bazel
and terminated by slash: -.bazel/
and the result is the same, computing directory structure takes about 5 mins, making IntelliJ slow to use.

**Comment by brendandouglas** [comment]
This should be fixed along with #160, by respecting excludes when computing directory structure.
