### ISSUE TITLE
Making this plugin work in pycharm

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/intellij#170]
Any chance this could be done?

**Comment by brendandouglas** [comment]
We don't plan to add support for any IDEs beyond the current three (IntelliJ (UE and CE), Android Studio, CLion).

That's because each additional IDE we support adds extra maintenance burden, and the other IDEs (pycharm, goland, webstorm, etc.) are functional subsets of these three. For example, IntelliJ CE/UE + the python plugin is a functional superset of PyCharm CE/UE.

There's some previous discussion in https://github.com/bazelbuild/intellij/issues/37 and https://github.com/bazelbuild/intellij/issues/61.
