### ISSUE TITLE
Test names with parentheses won't run in specs2

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#176]
Seems that specs2 sanitizes `()` to `[]` due to some junit displaying limitation:
https://github.com/etorreborre/specs2/blob/5d14719c4438ea01cf0c7cc7c4a52c1d8fd6c29b/junit/shared/src/main/scala/org/specs2/reporter/JUnitDescriptions.scala#L106-L111

Test names containing parentheses should be sanitized to match specs2.

**Comment by coreywoodfield** [comment]
I do see that specs2 changes `()` to `[]`, but I believe that's just for displaying, not for actually filtering the tests. If I have a test with parentheses (e.g. `"foo should (bar)" in { ...`), it is selected and executed properly when I use parentheses in the test filter (`bazel test "--test_filter=com.example.Test#\QFoo.bar should::foo should (bar)\E$"`) and is not selected or executed when I use braces in the test filter (`bazel test --test_filter=com.example.Test#\QFoo.bar should::foo should [bar]\E$"`), i.e. changing `()` to `[]` results in the specs2 specification not being selected instead of being selected
