### ISSUE TITLE
Support GoLand 2020.1

### ISSUE THREAD

**Issue by chartinmarrel** [bazelbuild/intellij#1770]
[GoLand 2020.1 has been released](https://www.jetbrains.com/go/whatsnew/?_ga=2.111114309.1154943414.1586514197-1625366715.1581010312) and latest Bazel plugin (2020.03.23.0.3) is flagged as incompatible.

<img width="364" alt="Screen Shot 2020-04-10 at 12 23 43 PM" src="https://user-images.githubusercontent.com/7941338/78985982-77faf600-7b2a-11ea-8a55-d1d5d5a2c4cf.png">

**Comment by muratbeser** [comment]
Hi Same work WebStorm

**Comment by austince** [comment]
There is a tracking ticket here for this suport: https://github.com/bazelbuild/intellij/issues/1567

**Comment by alice-ks** [comment]
By now, the Bazel plugin is compatible with 2020.1 and corresponding releases have been pushed to the plugin repository. Hence, I'm closing this issue. Please refer to other tracking issues if you're interested in the compatibility with newer IDE versions.

**Comment by benmcginnis** [comment]
This seems to be happening again? I just tried downloading the latest version (because it doesn't appear in the marketplace) and I get this message when I try to install it on Goland 2020.3.2:

<img width="456" alt="Screen Shot 2021-02-22 at 4 40 58 PM" src="https://user-images.githubusercontent.com/1206953/108773828-eb340d80-752c-11eb-9023-c5a392cfafd9.png">

**Comment by alice-ks** [comment]
The plugin is only compatible with 2020.2 so far and hence doesn't work in 2020.3. We're working on 2020.3 compatibility but are not done yet. #2102 tracks compatibility with 2020.3.
