### ISSUE TITLE
Can't automatically create run configuration with test rule that has "manual" tag

### ISSUE THREAD

**Issue by littleclay** [bazelbuild/intellij#209]
If I have a BUILD file with a `java_test` rule that has the tag "manual", IntelliJ won't create a run configuration when you click on the green arrow by the test. If you manually create a run configuration it will run the test.
<img width="184" alt="screen shot 2018-01-11 at 6 17 51 pm" src="https://user-images.githubusercontent.com/14144383/34856844-59f6d7dc-f6fc-11e7-89bd-082b00edebbb.png">

**Comment by brendandouglas** [comment]
The plugin's run configuration handling requires that the corresponding Bazel target be built during sync.

Targets tagged with 'manual' aren't included in wildcard expansions, so that target isn't in your project. Try including it explicitly in the .bazelproject 'targets' section, or else add these lines to build all 'manual' targets:
```
sync_flags:
  --build_manual_tests
```

**Comment by littleclay** [comment]
Oh, that makes sense and editing the .bazelproject fixed it. Thanks!
