### ISSUE TITLE
Errors building //proto:project_data_proto

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/intellij#2179]
- Ever since https://github.com/bazelbuild/intellij/commit/fe7b19d8e7626baf76d9bc0b667a0cc7a2d29585 this repo depends on floating version of bazelbuild/bazel - which is an antipattern of bazel reproducibility principle .
- In addition - the [proto import](https://github.com/bazelbuild/intellij/commit/fe7b19d8e7626baf76d9bc0b667a0cc7a2d29585#diff-94eed1bd05a73de6e02f1e535803c8e09bff64d29c91bc02e3e724d9c8056684L23) `import "bazel/src/main/protobuf/build.proto";` is wrong and should be `import "src/main/protobuf/build.proto";` . This current import line only magically works with bazel `3.7.0` (I don't understand how by looking at changelog of bazel).

**Comment by or-shachar** [comment]
Any comments?

**Comment by alice-ks** [comment]
You were right that we needed a different import line. That's fixed by now.

With 63a5456, the protos aren't pulled from the head of bazelbuild/bazel anymore but directly included in a specific version in this repo. So, I guess this also qualifies as not using a floating version of bazelbuild/bazel and hence I'm closing this issue. Feel free to reopen it if I misunderstood something.
