### ISSUE TITLE
External dependencies are not resolved in CLion

### ISSUE THREAD

**Issue by pumbaasdad** [bazelbuild/intellij#232]
Attempting to use the plugin with CLion, it appears that external dependencies are not being resolved.  The code at https://github.com/guyincognito24601/externalrepositorytest reproduces this issue.  If you open mainprogram in CLion, you will see that the application builds correctly, however, the IDE fails to find the path `external/bar/hello.h`.

![image](https://user-images.githubusercontent.com/32616257/35867310-75966f86-0b27-11e8-84a7-3f58733b5de4.png)

**Comment by RNabel** [comment]
I found a workaround if re-syncing, and re-building doesn't work: adding a symlink into the required `bazel-*` folder (for me it was `bazel-genfiles`), and then re-building etc. If it's still not recognised you can try invalidating your caches and restarting. This is super clunky but it works :)

**Comment by jvoung** [comment]
Writing the source as `#include "hello.h"`, instead, also works.

In the bazel compile cmdlines there are the flags:
(a) `-iquote .` (to make `#include "external/bar/hello.h"` work)
but there is also
(b) `-iquote external/bar` (to make `#include "hello.h"` work)

The IDE picks up both flags. It interprets be (b) okay, treating it the same as bazel (relative to the execution root), but the IDE treats (a)'s  "." as relative to the workspace root instead of the execution root, which may be why `#include "external/bar/hello.h"` is not working.

=======

Dir layout:
(a) execution root:
```
$HOME/.cache/bazel/_bazel_jvoung/c40bf559be0a031698aa3e13d27868f4/execroot/__main__/
├── bazel-out
//...
├── external
│   ├── bar
│   │   ├── BUILD -> $HOME/.cache/bazel/_bazel_jvoung/c40bf559be0a031698aa3e13d27868f4/external/bar/BUILD
│   │   ├── hello.h -> $HOME/.cache/bazel/_bazel_jvoung/c40bf559be0a031698aa3e13d27868f4/external/bar/hello.h
//...
├── hello.cpp -> $HOME/w/externalrepositorytest/mainprogram/hello.cpp
└── WORKSPACE -> $HOME/w/externalrepositorytest/mainprogram/WORKSPACE
```

but workspace root is just:
```
.
├── BUILD
├── hello.cpp
└── WORKSPACE
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by Elentary** [comment]
@sgowroji the issue still persists and is reproduciable with example repo from the description of this issue. Could you assign someone on this ?
