### ISSUE TITLE
Removing TypeScriptConfigService#getConfigs()  in 2021.1

### ISSUE THREAD

**Issue by anstarovoyt** [bazelbuild/intellij#2329]
Hi! I've noticed that you still use the method ``TypeScriptConfigService#getConfigs()`` although it is deprecated for more than one year. I've removed the method in 2021.1, because it produces a lot of performance issues. As an alternative, you can try to use ``TypeScriptConfigService#getConfigFiles`` but we also plan to deprecate this method too.
The best solution should be to avoid getting all the configs because projects can have hundreds or even thousands of them.

**Comment by anstarovoyt** [comment]
Usages:
``com.google.idea.blaze.typescript.DelegatingTypeScriptConfigService#getConfigs``
``com.google.idea.blaze.typescript.BlazeTypeScriptAdditionalLibraryRootsProvider#filesFromTsConfig``

**Comment by anstarovoyt** [comment]
also ``com.google.idea.blaze.typescript.DelegatingTypeScriptConfigService#hasConfigs`` is going to be deleted in 2021.1

**Comment by alice-ks** [comment]
Andrew, thanks for the heads-up. We seem to use `TypeScriptConfigService#hasConfigs` only for delegation, so we'll be able to just delete the delegating method. Thanks for pointing to an alternative for `TypeScriptConfigService#getConfigs()`. I expect that we'll switch to that alternative for now. As we need to derive the files from the tsConfig for a correct project setup when using Bazel, a better solution without these deprecated calls might be tricky.

As you've been wondering why we haven't switched away from the deprecated method: Our plugin is typically compatible with ~3 IntelliJ versions (e.g. currently still with 2019.3). It's easier for us to wait until all of the supported IntelliJ versions have the new method to which we should migrate instead of introducing unnecessary compatibility shims.

**Comment by anstarovoyt** [comment]
>hanks for pointing to an alternative for TypeScriptConfigService#getConfigs(). I expect that we'll switch to that alternative for now. 

then please note that ``#getConfigs`` must be not called from the rendering thread, because otherwise, it can produce freezes for users.

**Comment by alice-ks** [comment]
Thanks for the warning about the performance. Our calls are not on the EDT. We also figured out a way to not use the `TypeScriptConfigService#getConfigs()` method (see #2372).
