### ISSUE TITLE
External libraries do not maintain package structure

### ISSUE THREAD

**Issue by decentralgabe** [bazelbuild/intellij#2365]
![Screen Shot 2021-02-12 at 12 28 33 PM](https://user-images.githubusercontent.com/7622243/107820329-7a704280-6d2f-11eb-8b4f-423eb61507e4.png)

When using just go modules (not bazel) and you click on the “source” for a given import, you’re brought to the import package. With bazel, all the deps are single files — we lose the package structure of the deps. Viewing the deps in a given package is a useful feature. 

Is there a way to retain this functionality using bazel+goland?

**Comment by blico** [comment]
@AlexeyGy would you be open to a PR on this issue? 

I have a change making it so external Go libraries are displayed based on their import paths (similar to how external Go deps are shown without using the Bazel plugin). For example:

![image](https://user-images.githubusercontent.com/4976073/134405945-40d52af7-8da0-403a-af19-17f9f81cf290.png)

**Comment by AlexeyGy** [comment]
Hey blico,

this makes total sense from a user's perspective, especially for large projects withs lots of dependencies in individual go files. 

Since adapting the change would only touch the way that libraries are attached and made visible for IntelliJ in a slight way, I would not see any danger.

Happy to accept a PR.

Best regards,
Alexey

**Comment by sgowroji** [comment]
Closing this issue w.r.t this [comment](https://github.com/bazelbuild/intellij/pull/3848#issuecomment-1249998647) as it is already rolled out. @decentralgabe could you please verify the latest release and let us know if you have any queries on the same.
