### ISSUE TITLE
Feature Request: generate a temp binary target for main classes

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#247]
We have a flow where many developers who are working on a piece of code will write an improvised `main` method and will try to run it to see some results.
This is in code which is essentially a `library` rule and they just want to "play" with it.
In maven this works without a problem and what I wanted to suggest is to somehow generate a *_binary target (rule name by config?) when the developer clicks a main method (or Scala `app`) which isn't part of a binary target.
The binary target should have a main_class pointing to the element the developer clicked and should have a runtime dependency on the library target that exists

**Comment by ittaiz** [comment]
@chaoren @brendandouglas we want to start working on this, any objections?

**Comment by brendandouglas** [comment]
No objections, though I haven't given much thought to how this would be implemented.

**Comment by ittaiz** [comment]
Thanks!
If you have any thoughts we'd love to hear them.
Once we have leads we'll of course update here as well.

**Comment by hmemcpy** [comment]
@ittaiz and I were discussing on how to implement this, and after giving it some thought, propose the following solution:

Since this is primarily an IDE feature, we can pass the required context (specifically, the `main_class` value as an environment variable, using Bazel's `--action_env` parameter, which can be consumed from Skylark (using `repository_ctx.os.environ["FOO"]`). (Preferably, we would use `--define`, but it's not supported in Skylark, see https://github.com/bazelbuild/bazel/issues/4821)

We will create an implicit output binary target for every library, allowing calling it on demand, passing it the arguments from the envvar.

On the plugin side, we would need to create a new (low-priority) `RunConfigurationProducer`, and have it interact with (supported) targets.

WDYT?

**Comment by brendandouglas** [comment]
That sounds reasonable -- no objections to the plugin-side changes required.

Another possibility, which may not actually work -- construct a dummy BUILD file (with scala_binary BUILD target) on the fly, and pass it through to bazel together with the `--nocheck_visibility` and either `--package_path` or `--override_repository` flags. That will work equally (if it works) for multiple languages.

`--override_repository` would be preferable to `--package_path` (assuming they both work), because package_path invalidates the analysis cache.

**Comment by lberki** [comment]
Sadly, `--define` would not work. One could imagine a `genrule` writing a main class that calls into whatever class the user wants, but the eventual binary rule would also need to depend on the library rule in question, which cannot be influenced by `--define`. So the only thing that works is a repository rule, but if you write your own repository, you can also write whatever you want in the source file in it.

**Comment by hmemcpy** [comment]
@lberki thanks for this input, I have literally just discovered repository rules myself (seems that `os.environ` is exposed only in `repository_ctx`), so that wouldn't work either way. I'll try something else.

**Comment by hmemcpy** [comment]
After evaluating several approaches to this, and discussing with @ittaiz, the suggestion proposed by @brendandouglas seems most reasonable (at least, for Scala):

Given a `scala_library` at target `//foo`,create a *temporary* BUILD file (at location TBD, but anywhere under the WORKSPACE is fine, including `bazel-*` directories), containing a `scala_binary` with a `main_class`, and `deps=["//foo"]`, and run it with `--nocheck_visibility`. This seems to be enough to run an arbitrary target from another BUILD file.

The proposal is to have the plugin create such temp file in a subdirectory, consisting of e.g. a hash code of the scala_lib target starting+main_class name.

Anything obvious I'm missing here?

WDYT?

**Comment by hmemcpy** [comment]
Also, what utilities do I have in the plugin to create directories/files under the workspace root? Would appreciate any pointers to look at!

**Comment by chaoren** [comment]
Ah, we would need some kind of utility to analyze the library sources and spit out a main class if one exists. Would this be doable?

**Comment by hmemcpy** [comment]
@chaoren I tried this, but the biggest impediment is passing in the `main_class` parameter. Unless I am missing something critical, I cannot pass it dynamically from the outside, and AFAIK `--define` is not supported in Skylark.
Do you have ideas how this parameter would be passed?

**Comment by chaoren** [comment]
> write an improvised main method and will try to run it to see some results

For your use case, I think we could let the developer encode it in the source file with a comment.
Then we'll just check if any source files in the library contains the predefined pattern.
We'll have discoverability issues with this feature though. 

Or we can allow this feature only for "well structured" source files.
Grep for main declaration in canonical format, then grep for class declaration containing it.

**Comment by ittaiz** [comment]
@chaoren do you know if skylark code can access “—define”? I heard it can’t
but then someone said it’s:
“subject to makevar expansion and are available with the dictionary ctx.var”

**Comment by chaoren** [comment]
Just tried it out. It does work.

```
$ cat rule.bzl
def _impl(ctx):
    print(ctx.var)
    print(ctx.var["foo"])

target = rule(
    implementation = _impl,
)
$ cat BUILD
load(":rule.bzl", "target")

target(name = "target")
$ bazel build --define=foo=bar :target
DEBUG: rule.bzl:2:5: {"ANDROID_CPU": "armeabi-v7a", "CC": "/usr/bin/gcc", "AR": "/usr/bin/ar", "NM": "/usr/bin/nm", "LD": "/usr/bin/ld", "OBJCOPY": "/usr/bin/objcopy", "STRIP": "/usr/bin/strip", "GLIBC_VERSION": "local", "C_COMPILER": "compiler", "TARGET_CPU": "k8", "CROSSTOOLTOP": "external/local_config_cc", "STACK_FRAME_UNLIMITED": "", "CC_FLAGS": "", "ABI_GLIBC_VERSION": "local", "ABI": "local", "JAVA_TRANSLATIONS": "0", "COMPILATION_MODE": "fastbuild", "BINDIR": "bazel-out/k8-fastbuild/bin", "GENDIR": "bazel-out/k8-fastbuild/genfiles", "foo": "bar"}
DEBUG: rule.bzl:3:5: bar
INFO: Analysed target //:target (0 packages loaded).
INFO: Found 1 target...
Target //:target up-to-date (nothing to build)
INFO: Elapsed time: 0.297s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

**Comment by ittaiz** [comment]
amazing!
@hmemcpy we can revert back to our original plan...
maybe we need to report it in bazel repository to make sure they don't pull
the rug under our feet with this

**Comment by hmemcpy** [comment]
Great! I'll do just that, most of the code is the same, anyway :)

**Comment by hmemcpy** [comment]
This issue was fixed in https://github.com/bazelbuild/intellij/pull/288! It can be closed.

**Comment by petroseskinder** [comment]
@hmemcpy and @ittaiz does your change in #288 include support for arbitrary main methods in java projects?

**Comment by hmemcpy** [comment]
@petroseskinder We're using the fact it's possible to produce a deployable jar (by calling the implicit output target), and then simply executing the jar, passing it the main class name, but to be honest, I haven't tried this in Java.
If Java supports the implicit output to create deployable jar (and, from [the documentation](https://docs.bazel.build/versions/master/be/common-definitions.html#implicit-outputs) it seems that it might), then it should be a simple modification to the code in #228 to support Java.
Otherwise it may be more involved.
