### ISSUE TITLE
Unable to import a bazel project, if a directory already contains a .project file

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#275]
When trying to complete the import wizard, an error saying "Could not create project view file" will appear.
![image](https://user-images.githubusercontent.com/601206/38033343-8472fed6-32a8-11e8-9e21-5bbed95bd946.png)

Looks like such files may be leftovers from [Eclipse](https://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/misc/project_description_file.html)

To quickly reproduce:
```
$ mkdir foo
$ touch foo/.project
$ touch foo/WORKSPACE
```
Then try importing `foo` using the "Import Bazel Project" wizard.

**Comment by chaoren** [comment]
We changed to adding a `.project/` directory under where you choose to put your project data, so we can default to workspace root, without having the project data directory containing the entire workspace.
You could move the project data location elsewhere.
And I guess we can try to prevent the wizard from progressing if a `.project` already exists.

**Comment by hmemcpy** [comment]
> We changed to adding a .project/ directory under where you choose to put your project data, so we can default to workspace root, without having the project data directory containing the entire workspace.
Yeah, that was a most welcomed change! Thank you!

We've stumbled on this `.project` file issue when trying to migrate a project to bazel. It migrated successfully, but we couldn't import it into IntelliJ. The existing `.project` file contained Eclipse-specific metadata.
Just to make sure, if there's a **folder** called `.project` already, everything imports fine, the problem is just with the presence of a file.

**Comment by kodstark** [comment]
Hi, Directory .project cannot be created when Eclipse .project file exists there. It is kind of issue when you try to slowly migrate your Eclipse + Maven projects from to Bazel.  I would like to give users option to try Bazel and it means another item in guide "Please remove eclipse project files". IJ could at least override that file as both Eclipse and Idea setup are generated from pom.xml / BUILD or IJ could/should use different location than well known used by Eclipse. 

I must say it is a surprise seeing plugin creating .project directory - Google has internal Eclipse plugins for Bazel and does IJ compete with it using tricks? :smile: I always wondered why Eclipse chosen names like .project/classpath instead of Eclipse specific but it is too late - Eclipse is older than IJ!

**Comment by chaoren** [comment]
I didn't actually know eclipsed used .project already, sorry. You can put the project data directory anywhere you want though.

**Comment by kodstark** [comment]
@chaoren No worries. Not sure what you mean with putting the project data directory in other location? I just imported Bazel project and couldn't get through because of error "Could not create project view file" it tried to create .project directory. My steps are: 

1. Use existing Bazel workspace (top location with WORKSPACE file)
1. Generate from BUILD file: BUILD
1. Leaving defaults on next screen, "Project data directory" uses pre-populated value taken from first step

Do you mean to change "Project data directory" on third screen to put it outside of project? I see it is parent directory where .project is created. It is not good because it is auto-populated item and it also means "documentation" for user in my team.

Any chance to change default location from .project directory to more specific for IJ?

**Comment by chaoren** [comment]
> Do you mean to change "Project data directory" on third screen to put it outside of project?

Yes, you can change that to anywhere you want.

> Any chance to change default location from .project directory to more specific for IJ?

I'd like to keep .project for existing users. But add fallbacks if .project already exists and is not an intellij project. E.g., .project-00, .project-01, etc, until a name is available.

**Comment by chaoren** [comment]
> > Any chance to change default location from .project directory to more specific for IJ?
>
> I'd like to keep .project for existing users. But add fallbacks if .project already exists and is not an intellij project. E.g., .project-00, .project-01, etc, until a name is available.

We decided to go with .ijwb, .aswb, .clwb, for different IDEs.
1. Shorter than .project.
2. Don't expect anyone else to use those names.
3. Per-IDE, so it's impossible to accidentally open one IDE's project with another IDE.

**Comment by kodstark** [comment]
@chaoren Very good choice, better than .project-01! Thank you.
