### ISSUE TITLE
Breakpoint doesn't work for Kotlin in IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by jameslan** [bazelbuild/intellij#2832]
Installed `2021.07.19.0.1-api-version-212` in IntelliJ IDEA 2021.2.

Operation:

Open `rules_kotlin` project and place a breakpoint in a test, such as `testSrcJarGeneration` in `src/test/kotlin/io/bazel/kotlin/KotlinJvmBasicAssertionTest.kt`, then debug the test class using the icon on the gutter.

Expected:
Stopped at the breakpoint

Actual:
Test finished with all cases passed.

With plugin 2021.07.13.0.1 in IntelliJ IDEA 2021.1.3, it works as expected

**Comment by alice-ks** [comment]
Did you previously run a `Bazel sync`? Is the Bazel target covering `src/test/kotlin/io/bazel/kotlin/KotlinJvmBasicAssertionTest.kt` covered by the project scope of `.bazelproject`?

**Comment by mgenov** [comment]
I'm encountering the same issue on my side. The breakpoints where working in 2021.1 but not in 2021.2.

**Comment by alice-ks** [comment]
Thanks for the additional details! I could reproduce this issue. It seems to be caused by a different ordering of position managers in 2021.2 in the IntelliJ platform, which results in the KotlinPositionManager to be ordered after a custom one of this plugin which is intended for files outside of the project context. We'll still need to figure out how to fix.
