### ISSUE TITLE
Java 17 (Preview)

### ISSUE THREAD

**Issue by tadeoj** [bazelbuild/intellij#3080]
Hello.

Is there any way to indicate in the java_language_level option to use the preview mode?

In Java 17 preview you can use the new switch expressions and we are very interested.

Thanks.

**Comment by aarone** [comment]
i ran into the same issue and can contribute a change to support this. It looks like the plugin accepts a Java major version that is then mapped to an Intellij project language level. Language levels are (now?) a superset of Java major versions which is why the preview language levels aren't supported.

It looks like all of the possible language levels are defined in a enum (`com.intellij.pom.java.LanguageLevel`). Any issues with me extending the project view `java_language_level` option to support these enum names while keeping backwards compatibility with existing major versions?

**Comment by mai93** [comment]
@aarone I think we can review a PR that implements this extension.

**Comment by aarone** [comment]
thanks! see related PR

**Comment by mai93** [comment]
Fixed with #4061
