### ISSUE TITLE
Remove items in bazel command ran by the IJ plugin 

### ISSUE THREAD

**Issue by acrha** [bazelbuild/intellij#3082]
Using intellij plugin in AS, a build is always performed by this command: 
_Command: bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-75ec836c-2d54-43e5-8e9f-51bd95c3922f --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --config=android_arm64 --compilation_mode=dbg -s --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=~/.local/share/Google/AndroidStudio2020.3/aswb/aspect --output_groups=intellij-compile-android,intellij-compile-java,intellij-render-resolve-android -- folder:project_

I would like to build my project only with these parameters: 
bazel build --config=android_arm64 --compilation_mode=dbg -s //folder:project_

In a settings, I can modify only bazel path, not default parameters. How can I modify the default command hardwired in Intellij plugin? Is it possible to extend plugin to enable modification of parameters? Does exist a workaround at this moment?

**Comment by mai93** [comment]
Hello @acrha The command in your question is the one used in the sync operation, I do not think we can remove most of these parameters because they are needed for the plugin to collect information about the project (with the `intellij_info_aspect`) to properly set it up in the IDE. You can add more flags using; [build_flags](https://ij.bazel.build/docs/project-views.html#build_flags) and [sync_flags](https://ij.bazel.build/docs/project-views.html#sync_flags) in the `.bazelproject` file.

You can also run a build by creating a Bazel Command run configuration with command set to `build` and you can list only the flags you need under `Bazel flags`.
