### ISSUE TITLE
ERROR: Unrecognized option: --noexperimental_run_validations

### ISSUE THREAD

**Issue by maspe36** [bazelbuild/intellij#3183]
Trying to sync my bazel project with my BUILD files and the build is failing with 

`ERROR: Unrecognized option: --noexperimental_run_validations`

## Versions
CLion 2021.2.4
Bazel 0.23
Bazel plugin 2021.12.14.0.0-api-version-212

My bazel is old, but this is also called out as the minimum version of bazel by the plugin (For CLion 2019+)

**Comment by alice-ks** [comment]
I guess this occurs due to the old Bazel version, which doesn't have this flag. I see that somebody added this option to our code in 2020 and they likely didn't think about the minimal Bazel version specified for the plugin.

There's a way out for you: If you specify `blaze.sync.disable.valication.action=false` in `~/.intellij-experiments`, the plugin should not add the flag anymore. If the file doesn't exist, simply create it.
