### ISSUE TITLE
Kotlin (and java?): go like source layout,  classify co-located test sources as test sources. 

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#324]
We layout a lot of our kotlin modules and packages like go code, I often pop simple unit tests in the same directory as the package. It would be good to be able to have the sources auto classified -- this would mean  reading in test source via aspect processing in addition to using a directory glob. 

@brendandouglas Is there some support in the sync model currently for this (to support go maybe) ?

**Comment by brendandouglas** [comment]
There's no support for this currently -- we do associate sources with targets during sync, and we know which targets are tests. This works for Go, because Go rules (at least internally) have the nice behavior that test sources are specified directly in the test rule.

For java_test (and kt_jvm_test, I assume?), this isn't necessarily the case (you don't need to specify sources at all, just a test runner which could run tests from any class in the class path.

I don't think this is solvable via the aspect either -- to get this information you'd need to run the test. We could use heuristics to recognize test files though (and already do in several places).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
