### ISSUE TITLE
Checked in bazel run configurations in `.ijwb/.run` are unstable

### ISSUE THREAD

**Issue by beala-stripe** [bazelbuild/intellij#3259]
Some users in our repo have started creating and checking in run configurations in the `.ijwb/.run` directory. When a run configuration is added to this directory, it is loaded whenever the repo is opened.

The issue is that these run configurations are unstable when generated by the bazel plugin. Depending on much the plugin knows about the target kind, it will generate different run configurations. This dirties the repo and is confusing. Users never know if they're supposed to check in the changed file or not.

The source of this instability appears to be these lines:
https://github.com/bazelbuild/intellij/blob/ab966d7a0aa529207bfc403a7ba0ecf1878d7159/base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java#L255-L260

Here, the correct `handlerProvider` is detected. This depends on the target state and target kind. When a run configuration is modified, and the target is not synced, the kind is set to `null`. This causes `BlazeCommandGenericRunConfigurationHandlerProvider` to be selected. If the target is synced and the plugin knows the rule kind is `java_binary` it will select `BlazeJavaRunConfigurationHandlerProvider`. When this change is synced back to the run config in `.ijwb/.run` it dirties the repo.

I'm currently testing out the instructions provided [here](https://ij.bazel.build/docs/run-configurations.html#sharing-run-configurations) on how to share run configs, but it would be nice if the bazel plugin supported checking in `.ijwb/.run`.

This issue was also reported here https://github.com/bazelbuild/intellij/issues/2575 but it was closed without resolution.

**Comment by blorente** [comment]
Hello @beala-stripe 
The `.ijwb` directory is designed to be ephemeral, as it contains a lot of data relative to the user's filesystem (amongst other reasons). 
Please follow this comment for advice: https://github.com/bazelbuild/intellij/issues/3250#issuecomment-1517841688

To share run configurations, you may [store them elsewhere](https://www.jetbrains.com/help/idea/run-debug-configuration.html#share-configurations) in the repo, and import them [via the `.bazelproject` file](https://ij.bazel.build/docs/project-views.html#import_run_configurations)

**Comment by daniel-b2c2** [comment]
> To share run configurations, you may [store them elsewhere](https://www.jetbrains.com/help/idea/run-debug-configuration.html#share-configurations) in the repo, and import them [via the .bazelproject file](https://ij.bazel.build/docs/project-views.html#import_run_configurations)

Sorry to dredge this up 18 months later.

It seems that the documentation covers the import process, i.e. "Your project contains a `.bazelproject` file, and this references some runconfigs located in a folder which is your 'golden source', and intellij will import them so that they appear in the Intellij UI, and in doing so may write some stuff to ijwb, but just ignore that since this is intellij's private workspace".

It does not cover the return journey, i.e "I am a developer, and I have made a change to the run config via the intellij UI, and now I would like to share my changes with everybody else".

Is there a guide to this bit? I have a feeling it has to do with exporting the run configs back to the folder, but it would be nice if intellij would automatically write back to the 'golden source' directory that the `.ijwb` folder references, and then I could chose to share those changes (or not).

Again I could be wrong about the return trip but here's an example, in a recent project
- I exported the runconfigs
- It did create an xml file in the directory I chose.
- But I had to change it from `.ijwb` for some reason, and even after I told it to use a different directory it kept defaulting back to `.ijwb`).
- After exporting the runconfig, there were no changes to the .bazelproject file, shouldn't the bazelproject file have been updated with a reference to the newly exported runconfig? How is anybody in my team supposed to know this new config is there?
- So I manually edited the .bazelproject file, but I note that I have to add the file explicitly, I cannot add a wildcard for example. Is this expected?

Please tell me I'm holding it wrong 🙏
