### ISSUE TITLE
.bazelproject test_sources setting does not work with Python only directories

### ISSUE THREAD

**Issue by thomaslangston-mongodb** [bazelbuild/intellij#3784]
With a .bazelproject configuration like that below, "/python/tests" will not be detected as a Test Sources Root on Bazel IntelliJ plugin Sync. A manual edit in the Project view via the context menu option of "Mark Directory As -> Test Sources Root" also will not persist through the Sync.

.bazelproject

> directories:
>   .
> 
> targets:
>   //...:all
> 
> test_sources:
>   /python/tests/*
> 
> additional_languages:
>   python

**Comment by thomaslangston-mongodb** [comment]
Noting that I just tried this with .bazelproject like the one above in the [rules_python](https://github.com/bazelbuild/rules_python) repo and it seemed to mark test sources correctly, but it continues to not to work with my repo. My current theory is that a java test target is required to make it fail to mark python sources correctly.

**Comment by mai93** [comment]
Hello @thomaslangston-mongodb, I tried using the above .bazelproject with rules_python repo and I had to remove the `/` at the beginning of the `test_sources` path, i.e. using `python/tests/*` instead of `/python/tests/*` and the folder was marked as test source.

I also tried adding a java test under this same directory and it continued to be marked as a test source.

**Comment by sgowroji** [comment]
Hello @thomaslangston-mongodb, Did you get a chance to check the above [comment](https://github.com/bazelbuild/intellij/issues/3784#issuecomment-1231034367). Thanks!

**Comment by thomaslangston-mongodb** [comment]
@sgowroji I'm going to close this issue for now as I don't have the bandwidth to debug exactly what's different about my repo right now.
