### ISSUE TITLE
'google' branch builds are failing on Bazel CI

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/intellij#3813]
Downstream with Bazel@Head: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2572#0182617c-54b3-477d-bc90-7435acc36a7a

Regular pipeline: https://buildkite.com/bazel/intellij-plugin-google/builds/133#_

**Comment by mai93** [comment]
The failing tests are for "under-dev" versions and they are expected to fail until this version is fully supported that is why they are marked as soft-fail, so they should not affect the status of the Downstream pipeline if everything else passes. For example, if you checked the regular pipeline: https://buildkite.com/bazel/intellij-plugin-google/builds/133# the whole test is marked as "passed" because the only failing tests are marked as "soft-fail".

I already have PR: https://github.com/bazelbuild/intellij/pull/3812 that fixes those failures, we can enable the tests when it is merged.

**Comment by fweikert** [comment]
SGTM!
