### ISSUE TITLE
Bazel plugin removed the dafalt `Go Test` Run/Debug configurations.

### ISSUE THREAD

**Issue by LittleWat** [bazelbuild/intellij#3938]
#### Description of the issue. Please be specific.

Thank you for developing the nice plugin!
I am almost a beginner to bazel and intellij.

My project uses bazel and sometimes I would like to run `bazel test`, but most of the time I would like to run `go test`

But after I enabled the bazel plugin, the following default `go test` run/debug configuration UI was replaced with the bazel configuration.

![スクリーンショット 2022-09-18 16 47 22](https://user-images.githubusercontent.com/8979377/190891509-a3048cf7-c399-4846-9d1e-fa08e221c853.png)

I would like to use both (`Bazel test`, `Go test`) configurations.

Is it possible...?

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Just enabling the bazel plugin in go project.

#### Version information
IdeaUltimate: 2022.1.4
Platform: Mac OS X 12.2.1
Bazel plugin: 2022.08.24.0.1-api-version-221
Bazel: 5.2.0

**Comment by edposinitckii-hf** [comment]
I have provided a test repository to reproduce this behaviour: https://github.com/bazelbuild/intellij/issues/3527

**Comment by blorente** [comment]
Hello @LittleWat.
While this is technically possible, it's not a workflow we currently support. Because of the way IntelliJ plugins are structured, we have to choose how we're going to run every configuration. Currently, the Bazel plugin blankly asserts that it's going to run all the Go configurations. To enable Go configurations would take some work.

This is a feature I've been thinking about for a while, but haven't had time to do it. Giving it P2, but I'd be happy to give you pointers if you'd like to contribute a PR for it.

**Comment by blorente** [comment]
I'm bumping this issue to P3 and removing the milestone, as it's unlikely I'll have the time to work on it this year.
