### ISSUE TITLE
Prevent indexing of directories created for nested workspaces.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#395]
A nested workspace creates  `bazel-*` and `.project` )if the workspace is loaded into another ij product) directories. If the containing workspace is loaded intellij will start indexing these directories. 

The kotlin rules contain a JS example and this uses express (and soon android) . When I run local verifications IJ goes on a looooooong indexing spree. Please add some heuristics to ignore these directories

**Comment by chaoren** [comment]
You can exclude those from your containing workspace's `.bazelproject` file. You're probably using

```
directories:
  .
```

right?

**Comment by hsyed** [comment]
Yeah. I'll try excluding the folders to see if that prevents the index.

However, if I do exclude the folder it would mean  that I can't edit the files from the root workspace.

**Comment by chaoren** [comment]
You can still edit the files, but even if you can, why would you edit the bazel-* and .project files?

**Comment by hsyed** [comment]
Aah I see what you mean -- I don't want to edit the files in the bazel directories, but being able to inspect them in development is part of the workflow for developing rules. 

This does work:

```
-examples/node/bazel-node
-examples/node/bazel-bin
-examples/node/bazel-genfiles
-examples/node/bazel-out
-examples/node/bazel-testlogs
```

A slight improvement would be to allow simple globbing in the string  --i.e., `-examples/node/bazel-*`.  

Would it be a lot of work to make these directories "marked as excluded" and  ignored from indexing during syncing ?

**Comment by chaoren** [comment]
The logic for excluding the root `bazel-*` directories is here:
https://github.com/bazelbuild/intellij/blob/2bed7ad4f7bfd5da85b117984436a34aa58ec23d/base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java#L104

It's not based on globs, so we have to list the full path of each directory we're excluding. In order to exclude the ones from nested workspaces, we'd need to iterate through all project subdirectories to find nested workspaces. I don't think we want to do that.
