### ISSUE TITLE
[Bug] Clion can't index the path that specify by "-I" in copts

### ISSUE THREAD

**Issue by edwardmjm** [bazelbuild/intellij#406]
Minimal example to reproduce the bug:

WORKSPACE
```
```

include/gen.sh
```
echo '#include <vector>'
```

include/BUILD
```
genrule(
    name = "gen",
    srcs = ["gen.sh"],
    outs = ["A.hpp"],
    cmd = "$(location gen.sh) > $@",
)

filegroup(
    name = "Ahpp",
    srcs = ["A.hpp"],
    visibility = ["//visibility:public"],
)
```

A.cpp
```
#include "A.hpp"
#include <iostream>

int main() {
    std::vector<int> v;
    std::cout << v.size() << std::endl;
    return 0;
}
```

BUILD
```
cc_binary(
    name = "A",
    srcs = [
        "A.cpp",
        "//include:Ahpp",
    ],
    copts = [
        "-I$(GENDIR)/include",
    ],
)
```

With the above files, you will see Clion can't find `A.hpp` inside `A.cpp`. It shows red on `#include "A.hpp"` and can't access `A.hpp` by ctrl + left click.

This can be built by bazel correctly, but can't handle by Clion, should be regarded as a bug.

**Comment by jvoung** [comment]
Thanks for the repro, I can reproduce the issue.
The issue seems to be that the $(GENDIR) is not substituted before being passed on to the IDE.

If I instead do:
```
cc_binary(
    name = "A",
    srcs = [
        "A.cpp",
        "//include:Ahpp",
        "include2/nongen.hpp",
    ],
    copts = [
        "-I$(GENDIR)/include",
        "-Iinclude2",
    ],
)
```

with:

```
#include "A.hpp"
#include "nongen.hpp"
#include <iostream>

int main() {
    std::vector<int> v;
// ...
```

Where nongen.hpp is in include2/, then the `#include "nongen.hpp"` resolves okay.

**Comment by jvoung** [comment]
Agreed it's not great to hardcode. Just clarifying in case it helps with a workaround for now.

The most straightforward fix seemed to be to use expand_make_variables, but that's deprecated.

Some other alternatives:
* $(GENDIR) by itself is always an -iquote search dir (you can see this from "Show Compiler Info" action in the IDE for each .cpp file). So if you are willing to generate to "$(GENDIR)/otherdir/foo.h", and write the include as '#include "otherdir/foo.h"' it would just work without any copts. E.g., do the generation in BUILD instead of in include/BUILD. That's if you're willing to restructure the code slightly, or write the includes slightly differently.
* If you are willing to use the "includes" attribute instead of "copts", that *seems* to handle the $(GENDIR) substitution (but see the warning in the docs about it automatically spreading to all dependencies of a target, which you might not want, since it can then spread quite a bit from a low level target https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.includes).

**Comment by edwardmjm** [comment]
Hi, that's true.
My current situation is, the team put cpp code under:
`cpp/...`
But the team don't want to have the cpp prefix in the include statement of C++ like:
`#include "cpp/..."`
Use "includes" attribute has a side effect that bazel will use `-isystem` instead of `-iquote`. That will cause gcc suspend its warning under the path of `-isystem`. So that's not ideal. If bazel can give an option that choose among `-isystem` / `-iquote` will be greate. But at the moment, that's the case.

So, they are not very good solution in my case.

**Comment by jvoung** [comment]
https://github.com/bazelbuild/intellij/commit/e76fdadb0bdabbe2be913cba03d9014eb2366374#diff-3a3a2e2292228746349df940a4d3d83bR314
