### ISSUE TITLE
Gazelle target to run on Sync has no option

### ISSUE THREAD

**Issue by jexelrud** [bazelbuild/intellij#4438]
#### 

- Open a project in GoLand
- Select Settings
- Select Bazel Settings
- Click on combo of Gazelle target to run on. Sync
- No option is displayed

#### Version information
GoLand: 2022.3.2
Platform: Mac OS X 13.2
Bazel for IntelliJ plugin: 2023.01.24.0.1-api-version-223
Bazel: 6.0.0

**Comment by blorente** [comment]
@jexelrud Thanks for the report! Unfortunately, that combobox in the settings menu will only display past values that you have set. Because that configuration is global in your IDE (persistent across projects), it can't read your project to figure out which gazelle targets you can list there.

However!

What you _can_ do, and in fact what we recommend you do, is configure the gazelle target you want _in your project view file_ (your .bazelproject file), using the `gazelle_target:` field. This will also not give you autocompletion, but it will allow you to check the configuration into the repository and share it with other members of the project.

An example on how to configure the project view file can be found in [`examples/go/with_proto/.bazelproject`](https://github.com/bazelbuild/intellij/blob/1de5317fd37ed4fa747d976d82d4bc9db68e3554/examples/go/with_proto/with_proto.bazelproject#L10).

@mai93 , where would be the best place to document the `gazelle_target` field?

**Comment by mai93** [comment]
added `gazelle_target` section to the project view documentation: https://ij.bazel.build/docs/project-views.html#gazelle_target
