### ISSUE TITLE
Support Scratches

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#449]
https://www.jetbrains.com/help/idea/scratches.html

Attempting to create a new Java scratch file results in this:

<img width="663" alt="screenshot 2018-11-19 at 13 26 32" src="https://user-images.githubusercontent.com/33242106/48683398-110d3200-ec01-11e8-9ee3-9e2c554a2f0c.png">

**Comment by brendandouglas** [comment]
Does this happen when creating a scratch file, or when trying to run one?

**Comment by brendandouglas** [comment]
Had a quick look -- it's just when executing. This is expected, because the plugin doesn't have the required information to run execute it with bazel, and the bazel plugin handles compilation.

We're not planning to support executing java binaries or compiling java source code without an associated bazel target.
