### ISSUE TITLE
Toolchain not being picked up

### ISSUE THREAD

**Issue by Jonpez2** [bazelbuild/intellij#463]
I've been trying to make a seamless integration between my bazel toolchain setup and clion, and failing.  I believe I've replicated my problem using data from the test data packaged with bazel.  I took the code out of https://github.com/bazelbuild/bazel/tree/master/src/test/shell/bazel/testdata/bazel_toolchain_test_data, copied it into a new directory, fixed up the links, added a call to register_toolchains, and was good to go.
The specific bug I'm experiencing is that even though the command line compile (blaze build //:hello) works fine, clion is unable to resolve any of the system includes in hello.cc.  I get red squigglies under all of the includes at the top of the file, std:: is undefined, as is NULL and EXIT_SUCCESS

I'm using bazel v 0.19.0, clion 2018.2.6 and clion bazel plugin 2018.11.12.0.4.

One other thing which took me _forever_ to debug was that a mispelling in the toolchain_type member of toolchain fails silently, with no red squigglies or bazel error; you simply end up with 'no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type'.  To replicate that, simply change both toolchain_type values in tools/arm_compiler/BUILD to be @bazel_tool instead of @bazel_tools.

Thank you for your help, and for making an awesome product!

**Comment by jvoung** [comment]
I think the problem is that we don't do "resolveToIncludeDirectories(executionRootPath)" for the toolchain supplied flags that we'd do from BUILD target attribute supplied flags (like here for a "cideinfo" https://github.com/bazelbuild/intellij/blob/02b148713798c71d86121e3c22ca5ef5470cb08b/cpp/src/com/google/idea/blaze/cpp/BlazeCWorkspace.java#L221).

====

Debug info
* add cidr.show.compiler.info=true to clion-2018.2/bin/idea.properties
* restart IDE, then open hello.cc, and use "Find Action" (ctrl+shift+a), then type "Show compiler info"

From there, I see a dump of compiler switches.
In particular:
-isystem
	external/org_linaro_components_toolchain_gcc_5_3_1/arm-linux-gnueabihf/include/c++/5.3.1/arm-linux-gnueabihf

However, at the end there's a section that says "Header Search paths", and that section doesn't have the "c++/5.3.1" directory.

Because we aren't processing those flags with resolveToIncludeDirectories(executionRootPath) it's missing the execroot prefix like 
/home/jvoung/.cache/bazel/_bazel_jvoung/94fe03a4b5f41858095550cc3173afb9/execroot/__main__

**Comment by Jonpez2** [comment]
OK.  Note this is a simple pull up out of the bazel repo test dir, so I thought it would be a pretty reasonable starting point.  Is there a better example out there I should be using?

I'll try to make this one work though.

**Comment by katre** [comment]
Oh, I didn't realize this wasn't a reduced version of your actual project. I suspect the issue is that I am not set up for ARM development.

Unfortunately, I can't comment on the CLion issues, which seems to be the problem @jvoung flagged related to resolveToIncludeDirectories. @jvoung would be the best person to determine if there's a workaround for you.

**Comment by Jonpez2** [comment]
Yeah I agree, the best avenue of attack is @jvoung 's point.  I await instructions :)

But: it's interesting, actually - does the test from the bazel repo work on your box?  It's this one here: https://source.bazel.build/bazel/+/master:src/test/shell/bazel/bazel_toolchain_test.sh .  I was trying to just lift out of the main repo's tests to make it easier to make a test for the plugin, you see; but if the main repo test isn't set up right then I guess that won't work...

Thanks for looking!

**Comment by katre** [comment]
@Jonpez2 That's interesting. I did the same thing you did (defined `testdata_path`, and then manually ran the commands from that test), and that did work.

The only changes I see that you've done are the WORKSPACE and .bazelrc, so it must be one of those that confuses Bazel.

In either case, I'm glad I could figure out why the sample didn't work properly!

**Comment by jvoung** [comment]
Put in a change doing more resolveToIncludeDirectories in the next plugin release (2019.02.11).

**Comment by jvoung** [comment]
more `resolveToIncludeDirectories` 
 around https://github.com/bazelbuild/intellij/blob/e76fdadb0bdabbe2be913cba03d9014eb2366374/cpp/src/com/google/idea/blaze/cpp/IncludeRootFlagsProcessor.java#L91
