### ISSUE TITLE
GoLand 2018.3 move refactoring not working 

### ISSUE THREAD

**Issue by mennanov** [bazelbuild/intellij#466]
When I try to use "Refactoring -> Move" I get an error  "The target directory should be located inside the project.", however the directory path looks correct.

<img width="518" alt="screen shot 2018-12-04 at 20 31 17" src="https://user-images.githubusercontent.com/1451079/49490212-c0eabe00-f803-11e8-9a5e-9acbba35e126.png">

It was also the case for GoLand 2018.2.

**Comment by chaoren** [comment]
https://youtrack.jetbrains.com/issue/GO-6548

**Comment by chaoren** [comment]
It works fine in regular Go projects because their source code usually reside in the project directory.
The bazel plugin keeps source code separate from the project directory.
It's possible to recreate the issue without the bazel plugin by just adding source roots from outside of the project directory.
