### ISSUE TITLE
Regression: plugin creates broken project libraries for java_imports in secondary package path

### ISSUE THREAD

**Issue by keithkml** [bazelbuild/intellij#468]
My company cannot upgrade to the latest version (v2018.11.12) because most of the IntelliJ Project Libraries generated from `java_import` rules are broken - they refer to jar files which do not exist. I presume this was an unintended side effect of _Resolve short-form references to external workspace targets_ from the release notes.

The issue is that the libraries are created as if all files are present in the *first path* on the [Bazel package path](https://docs.bazel.build/versions/master/command-line-reference.html#flag--package_path).

# Steps to reproduce

My employer won't let me create Gists or public GitHub projects, so I'll just paste the important files. You will need to fill in the mostly blank files A.java, B.java, etc. And you will need to use basically any jar file for `libf-copied-from-bazel-bin.jar` and `libg-copied-from-bazel-bin.jar`

## .bazelrc
```
query --package_path=%workspace%:%workspace%/fuse_mount
build --package_path=%workspace%:%workspace%/fuse_mount
```

## BUILD
```py
java_binary(
    name = "a",
    srcs = ["java/my/pkg/A.java"],
    main_class = "A",
    deps = [
        ":b",
        ":d",
    ],
)

java_library(
    name = "b",
    srcs = ["java/my/pkg/B.java"],
    deps = [":c"],
)

java_library(
    name = "c",
    srcs = ["java/my/pkg/C.java"],
)

java_library(
    name = "d",
    srcs = ["java/my/pkg/D.java"],
    deps = [
        ":c",
        ":import_f",
        "//otherpkg:e",
        "//otherpkg:import_g",
    ],
)

java_import(
    name = "import_f",
    jars = ["libf-copied-from-bazel-bin.jar"],
)
```

### fuse_mount/otherpkg/BUILD
```py
java_library(
    name = "e",
    srcs = ["java/some/otherpkg/E.java"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "import_g",
    jars = ["libg-copied-from-bazel-bin.jar"],
    visibility = ["//visibility:public"],
)
```

**Comment by brendandouglas** [comment]
Thanks for letting us know. We haven't actually intentionally supported package_path for a very long time. We used to support it ~1 to 2 years ago, but removed support because it was imposing too much complexity on the code base, and was no longer used internally (or by external plugin users, as far as we knew).

So this was previously working for you entirely by accident.

That short-form path change didn't cause this -- that just affects how references in BUILD files resolve. The reason why this use case broke:

- because we don't search all package paths, the artifact locations seen by our aspects are incorrect for the class jar and source jar in this situation, but correct for the ijar (which is the raw bazel-out/blah/genfiles path)
- previously the library attached to the project would use the ijar + source jars (if present). As of this release, we use the class jar in situations where there are no source jars, so users see more useful information when navigating to libraries.

You can go back to the previous behavior by 'blaze.use.class.jar=0' to $HOME/.intellij-experiments

Alternatively you could work around this by exposing source jars in your targets (causing the plugin to use ijars instead of class jars for the libraries).

Longer-term though, package_path is not something we're planning to support, and I wouldn't rely on it working with this plugin.

**Comment by keithkml** [comment]
Good to know - thanks. We did notice some weird issues with source jars which we have yet to look into, but your comments will likely be helpful with that investigation 😄 

FYI we have over 300 IntelliJ users at my company, and we are inextricably tied to `package_path` for the foreseeable future. (We kinda [presented about this](https://www.youtube.com/watch?v=rQd9Zd1ONOw) at BazelCon 2018.) Not all of those users are on Bazel yet, but they will be within 6-12 months.

**Comment by alice-ks** [comment]
There hasn't been any updates in over two years. Is this issue still a thing? If so, please re-open this issue.
