### ISSUE TITLE
"Copy BUILD Target String" is missing in some cases

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/intellij#475]
## background
We love the "Copy BUILD Target String" straight from class feature! 
(right click a class, and select "Copy BUILD Target String" from the menu)
It greatly helps us when we want to know the corresponding label of a certain file.
![image](https://user-images.githubusercontent.com/2962963/50156851-82133880-02d8-11e9-82a5-1746626f3640.png)

## issue
Unfortunately there's a use case that this feature fails to work.
- The `BUILD` file in the same level as the source file doesn't have a `java_library` or `scala_library`, only `filegroup` that groups all sources
- The actual target that compiles the sources is on a different BUILD file (for us, and I hope it's some kind of convention - it would be found in one of the upper levels). 

In that case the right click menu would lack the "Copy BUILD Target String" option.
![image](https://user-images.githubusercontent.com/2962963/50156887-9fe09d80-02d8-11e9-9679-9f3426a165f2.png)

## repro
https://github.com/or-shachar/bazel-sample-repo/tree/find_label_example
(note the branch name `find_label_example`)
See the difference between the behavior on:  `MyCaseClass`, `NoBuildFile.scala`, `CycleA.scala`

(This issue was checked with Intellij `2018.3.1` and latest plugin version `2018.11.12.0.4` on MacOS)

**Comment by ittaiz** [comment]
Just checked and this is still happening at HEAD (also IJ 2019.2.4).
Following a [discussion](https://bazelbuild.slack.com/archives/CM8JQCANN/p1566481600003600) I had with @jin about this a few months ago I checked what happens if I comment out the `filter` [line](https://github.com/bazelbuild/intellij/blob/bb953d070b93d92b3c175bb44599ad11d1a4324b/base/src/com/google/idea/blaze/base/actions/BuildFileUtils.java#L79) in `BuildFileUtils#findBuildTarget`  and it indeed fixes the repro.  

@brendandouglas given the above discussion I understand I can't just comment it out since cpp code needs this but I was wondering if you'd be open to a PR that applies the filter only if the files are CPP related (probably by using the [LanguageClass](https://github.com/bazelbuild/intellij/blob/bb953d070b93d92b3c175bb44599ad11d1a4324b/base/src/com/google/idea/blaze/base/model/primitives/LanguageClass.java#L26))?

**Comment by chaoren** [comment]
I think instead of filter we can change it into an order and it'll still work. I.e., label with bazel package closest to file preferred.

**Comment by ittaiz** [comment]
@brendandouglas I added the fix to our fork. If you’re interested I’d be happy to contribute it https://github.com/wix-playground/intellij/commit/aa9895d35018606b295b04f758bb25bef979922c

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
