### ISSUE TITLE
Structure of project view files

### ISSUE THREAD

**Issue by libsamek** [bazelbuild/intellij#499]
Hi,

I have project structured as follows:
```
project-root
  service1/
  service2/
  some-other-stuff/
  other-file1
  other-file2
  WORKSPACE
```

My question is: How to structure project view file to include service1, service2, WORKSPACE but not some-other-stuff dir and no other-file1, other-file2?

I have tried specifying service1, service2 but then I have no way of including WORKSPACE file. 

I have also tried this, including whole dir, but excluding not wanted files/directories, but I still see those files in project within IntelliJ:
```
directories:
  .
  -some-other-stuff
  -other-file1
  -other-file2
...
```

How to approach this?

**Comment by brendandouglas** [comment]
Excluding the subdirectories with a '-' as you mentioned is the intended approach.

Is it possible the directories are being excluded, but you're still seeing them because 'show excluded files' is enabled in the project tab settings?

'File > Project Structure' will show you exactly which directories are excluded.

**Comment by alice-ks** [comment]
Brendan provided some guidance in the previous comment. As there hasn't been any further questions since then, I'm assuming that Brendan's help was sufficient.
