### ISSUE TITLE
Support HotSwap / Reloading Classes

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#50]
IntelliJ supports "hotswapping" (reloading) classes while debugging a process. https://www.jetbrains.com/help/idea/2016.3/reloading-classes.html

For example, open this sample project https://github.com/dfabulich/bazel-intellij-hotswap

Import it as a Bazel project, open `X.java`, and set a breakpoint on line 14.

```java
System.out.println("hello");
```

Run `//:x` in Debug mode so you hit the breakpoint. Now replace the word "hello" with the word "goodbye"

Expected: Build and hotswap the class
Actual: Nothing happens at first, because you have to Make the project by hand. But, of course, you can't, because of issue #34. "Another command (pid=####) is running.  Waiting for it to complete..."

**Comment by dfabulich** [comment]
When I apply my work around for issue #34, documented here https://github.com/bazelbuild/bazel/issues/2337#issuecomment-276295577 in a comment on the corresponding issue in `bazel`, I can get a _bit_ farther, but the bug remains.

With the `tools/bazel` script in place, I'm able to launch the build while the X process is running, but running that build doesn't initiate hotswapping. The process continues to print "hello" even though the jars have changed out from underneath it.

**Comment by dfabulich** [comment]
There was a good discussion about this on the mailing list. https://groups.google.com/d/msg/bazel-discuss/0yjJvIk6jKk/9kNW4Vf6BgAJ

**Comment by ittaiz** [comment]
Hey, just wanted to say this feature is really important for us as well. We don't debug in the day to day but every once in a while when you need it the hotswapping part of it is crucial.

**Comment by hibissscus** [comment]
Hi, do you have any plans to add ability to add hot swap functionality to the IntelliJ bazel plugin? I am wonder to use it together with http://hotswapagent.org/ and DCEVM. Already tried it out but without success, because when we changing class and calling "reload class" inside IntelliJ, bazel are not care about this changed class.

**Comment by brendandouglas** [comment]
We do plan to support this. It's just a matter of finding time to do it.

I can't yet give an accurate estimate of when it might be done, as there are many higher priority tasks pending. I'll update this thread when we get to starting it.

**Comment by brendandouglas** [comment]
As of v2017.09.25, there's hotswap support for java_binary targets.

It's integrated into IntelliJ's 'reload changed classes' action, which will now trigger a blaze build to determine and compile the changed classes.

We don't have any current plans to add hotswap support for any other blaze rule types.

**Comment by ittaiz** [comment]
Are you open to accepting contribution for other jvm binary rules? for
examples scala specs2 tests.

**Comment by brendandouglas** [comment]
Absolutely! I just had a quick look, and it appears scala binaries are debugged using much of the same code (via BlazeJavaDebuggerRunner, BlazeJavaRunProfileState, etc.).

So supporting scala_binary might even be as simple as:
- add Kind.SCALA_BINARY to HotSwapUtils#canHotSwap
- ensure that scala_binary rules provide java_common, with compilation_info filled in (I suspect this is already the case?), so that //aspect/java_classpath.bzl will function as required

**Comment by ittaiz** [comment]
Awesome!
Thanks!
Cc @hmemcpy- we need to get this in our list

**Comment by brendandouglas** [comment]
It doesn't work for test targets at the moment. The reason being, those are much more difficult to run (correctly) without tying up the Bazel server.

For binary targets, we get around this by using 'bazel run --script_path=...', but there's no such option for test targets (presumably because Bazel needs to wait for the tests to complete to report results).

**Comment by ittaiz** [comment]
What do you mean "tying up the bazel server"?
additionally, any objections to opening an issue re hotswap for tests?

**Comment by brendandouglas** [comment]
Only one bazel invocation can be run at a time, so running 'bazel test' as part of debugging will prevent any subsequent 'bazel build' until the test completes.

We use 'bazel build' to determine the list of classes which have changed (and produce the compiled class files), to pass to the running jvm used for debugging.

**Comment by ittaiz** [comment]
I see. Thanks

**Comment by hmemcpy** [comment]
Alright, I sent a PR that makes scala binaries support HotSwapping (via the Reload Changed Classes menu action).
This required a slight change in the `//aspect/java_classpath.bzl` to return the correct runtime jars.

I noticed that the current implementation does not have feature parity of that in "plain" java binaries - the ability to hotswap automatically on recompilation.
A little digging around led me to the implementation of `HotSwapUI` in IntelliJ core, implementing a `CompilationStatusListener`, and performing a hotswap on its `compilationFinished` event.

This sounds a feature worth having. I can open a separate issue for having it implemented!

**Comment by brendandouglas** [comment]
Because we don't hook into IntelliJ's compilation actions, that would be a bit tricky.

Also, hotswapping requires a special kind of recompilation (a bazel build invocation building only that binary, with our aspect attached), so we can't just listen for a bazel sync (the normal compilation event).

Personally, I just have the 'reload changed classes' action bound to a hotkey, and treat that as the recompile command when debugging.

**Comment by hmemcpy** [comment]
Fair enough. To be honest, I don't use this feature very often, and when I do, it's usually from debugging tests. Unfortunately that's even harder to implement, as you've said :)
I will amend the new issue I've opened to ask for the actual feature we need: hotswapping inside tests.

**Comment by tybook** [comment]
I think this can be closed since hotswapping now works for Java/Scala binary targets via the **Run -> Reload Changed Classes** menu action and we created #181 for supporting test targets.

**Comment by alice-ks** [comment]
Closing in accordance with the last comment from Dec 2019.
