### ISSUE TITLE
Query sync is referring unavailable genzip tool

### ISSUE THREAD

**Issue by idanakav** [bazelbuild/intellij#5193]
### Description of the bug:

`tools/genzip:build_zip` is [used](https://github.com/bazelbuild/intellij/blob/53cf0680dab7ea2dac3c1589ac69b268d596aee3/aspect/build_dependencies.bzl#L403) in order to generate an AAR file for the IDE, however that label refers to a target which does not exist on the repo which causing the sync to fail.

I understand query sync is experimental and in active development, yet, thought it worth highlighting the issue in case it got missed. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Enable query sync
2. Run sync
3. Observe error
```
 package 'tools/genzip': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

### Which Intellij IDE are you using? Please provide the specific version.

AI-221.6008.13.2211.9619390

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

build on recent sha: 4cba72f7b094ed58fa179a90b87f13f33eb31689

**Comment by mai93** [comment]
this is fixed with https://github.com/bazelbuild/intellij/commit/3840c00c87abf6df67ac16c26b72778d89fd44ac

**Comment by mai93** [comment]
In the last SIG meeting I mentioned that there are still problems that need to be fixed with query-sync but you can work around them if you want to try it out. The problems I found are:
- The bazel invocation for build dependencies expects the WORKSPACE directory to contain a BUILD file to be able to use the aspects defined in the copied //:.aswb.bzl file
- Build dependencies action does not handle the case of `directories: .`, i.e. all directories in workspace. This causes it to not recognize any files (no dependencies are available to them)
workaround: specify exact directories in the project view file

**Comment by idanakav** [comment]
@mai93 ty, I'll give it a try and report back if I notice any other issues.
