### ISSUE TITLE
How to figure out what version(s) of Bazel a specific version of the plugin supports?

### ISSUE THREAD

**Issue by simingweng** [bazelbuild/intellij#534]
our project is stuck with bazel 0.14.1 right now, the latest of the plugin has of course dropped support for this older release. How can I figure out the last version of Bazel Intellij Plugin that still supports that version of Bazel?

I think generally, it would be great to have a compatibility matrix of (Bazel Intellij Plugin version, supported Bazel version(s), Intellij IDE version(s)/Android Studio version(s)). Or please help to point to which source file actually defines the supported or cut-off version of Bazel the plugin supports.

**Comment by brendandouglas** [comment]
In general, we don't maintain support for Bazel versions older than a couple of months. This is because Bazel makes frequent backwards-incompatible changes between releases, and it's simply not practical to continue supporting older versions.

BazelVersionChecker is the source file which defines this (though it's not always kept up to date). During sync, the plugin will error if you're on a bazel version which is known to be incompatible.

Otherwise, we can't practically maintain a compatibility matrix, we simply don't have the bandwidth for this sorry.
