### ISSUE TITLE
PackageParser leaks threads and leads to "fork: No child processes" errors

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/intellij#5362]
### Description of the bug:

We have found a situation where syncing a project in IntelliJ occasionally causes our machines to become unusable because it's not possible to spawn any more processes. Our environments have a max soft `ulimit -u` of 8192 (not sure how common that is), and the PackageParser persistent worker causes us to bump into that.

When the problem was happening in my machine, I could end up looking at the 4 running instances of the PackageParser and found that each of them had about 2000 live threads.

Looking at the code, it seems that the persistent worker is creating a fresh thread pool for each work requests. I'm guessing that, at some point, these pools aren't reclaimed and they pile up.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Don't know. This problem happens pretty much randomly for us. I do not know what exact set of steps leads us to trigger this problem.

### Which Intellij IDE are you using? Please provide the specific version.

IDEA CE 2023.1.1

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2023.08.15.0.1-api-version-231

### Any other information, logs, or outputs that you want to share?

As a workaround, passing `--strategy=JavaPackageManifest=sandboxed` to our `sync_flags` helps avoid the problem.

Also, while the problem is active, using `ulimit -u 10000` or similar in an already-open shell helps provide extra processes to troubleshoot the problem.

**Comment by JohnnyMorganz** [comment]
We are also hitting this problem in a reasonably large Java repo (~6000 targets, 55k java files). I can consistently reproduce this by performing a cold sync of such a repo (`bazel clean --expunge`, disable remote cache, then run IntelliJ sync). 
Running `ps a -eo nlwp,pid,args --sort nlwp`, I can see the 4 persistent workers each have 6000-7000+ open threads

As you mention, the fixed threadpool here is unbounded and not cleaned up, and the problem most likely manifested after the switch to using persistent workers in https://github.com/bazelbuild/intellij/pull/3686 (as originally the sandboxed action would just get killed afterwards)
https://github.com/bazelbuild/intellij/blob/15cfacbbe129c02d37660e2686a6f004111a114f/aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java#L182-L184 

To fix it, it could potentially be switched to using [`newCachedThreadPool`](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/util/concurrent/Executors.html#newCachedThreadPool()), or otherwise lower the limit rather than using max num. of available processes (maybe a fixed size or a variable factor, or it should be user configurable?). Happy to open a PR if there is an agreed solution.

For now, the workaround seems to work. I don't see a negligible performance impact on syncing, but maybe persistent workers would help in future.

**Comment by mai93** [comment]
I think changing it to a user configurable number can be a good approach, @tpasternak what do you think?

**Comment by tpasternak** [comment]
So configurable number might be useful (to experiment? maybe in some cases it would be good to set the number higher than cpu threads?) but still it is clearly a bug so I'd accept it with or without configurability
