### ISSUE TITLE
Cannot resolve size_t 

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#553]
Hello. I am using the clion bazel plugin successfully but it cannot resolve some symbols for the standard library like size_t!  Any ideas what I may need to tweak to get this working? I am using a custom cc toolchain with llvm (very similar to tensorflow build toolchain).

Specifically, my editor is saying: `Unknown type name 'size_t'`

**Comment by SharmaNishant** [comment]
+1

**Comment by daghub** [comment]
We have the same issue. The root cause for us is that in our tool chain paths such as isystem_directories and builtin_include_directories are relative to the execroot. The bazel plugin captures the information with its aspect, but when CLion tries to parse the code the working directory is not execroot, it is the repo root. Hence, it will not be able to find headers. This can be seen through strace:
Using strace to figure out what file accesses are done by CLion is revealing:

[pid 31102] stat("/home/dag/ext/werkstatt/external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1/include", 0x7f79268a96b0) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1", 0x7f79268a9580) = -1 ENOENT (No such file or directory)
[pid 31102] stat("external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1/include", 0x7f79268a96b0) = -1 ENOENT (No such file or directory)
[pid 31102] stat("external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1", 0x7f79268a9580) = -1 ENOENT (No such file or directory)
[pid 31102] stat("external/clang_3_9_1_x86_64_linux/lib/include", 0x7f79268a96b0) = -1 ENOENT (No such file or directory)
[pid 31102] stat("external/clang_3_9_1_x86_64_linux/lib", 0x7f79268a9580) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/.clang-tidy", {st_mode=S_IFREG|0664, st_size=4889, ...}) = 0
[pid 31102] open("/home/dag/ext/werkstatt/.clang-tidy", O_RDONLY|O_CLOEXEC) = 6
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/src/core/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/src/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/.clang-tidy", {st_mode=S_IFREG|0664, st_size=4889, ...}) = 0
[pid 31102] open("/home/dag/ext/werkstatt/.clang-tidy", O_RDONLY|O_CLOEXEC) = 6
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/src/core/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/src/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/fusion/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31102] stat("/home/dag/ext/werkstatt/platform/.clang-tidy", 0x7f79268a9a50) = -1 ENOENT (No such file or directory)
[pid 31042] lstat("/tmp/clion-clang-tidy", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 31042] open("/tmp/clion-clang-tidy", O_RDONLY) = 12
[pid 31042] lstat("/tmp/clion-clang-tidy", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 31042] rmdir("/tmp/clion-clang-tidy") = 0

It is looking for headers in
/home/dag/ext/werkstatt/external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1
and
external/clang_3_9_1_x86_64_linux/lib/clang/3.9.1
(etc)
These  are not the valid locations, because the files are really in the execroot not in the repo.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
