### ISSUE TITLE
IntelliJ can't resolve classes generated from protobufs

### ISSUE THREAD

**Issue by philwo** [bazelbuild/intellij#82]
### How to reproduce:
- Unpack provided minimal example: [prototest.zip](https://github.com/bazelbuild/intellij/files/969764/prototest.zip)
- Import provided protobuf.bazelproject into new IJWB project.

### Sanity check:
- bazel clean --expunge; bazel build :all; bazel run :prototest 
- Builds fine and prints: "Hello, John Doe"

### Expected result in IDE:
- "Person" class generated from test.proto can be resolved in the IDE.

### Actual result in IDE:
- "Person" class cannot be resolved: <img width="446" alt="screen shot 2017-05-02 at 09 55 02" src="https://cloud.githubusercontent.com/assets/504652/25608988/7192cb8c-2f1d-11e7-91e2-8b5321602287.png">
- None of the actions in "Bazel > Sync" in IJWB helps, nor does "File > Invalidate Caches / Restart". The IJWB sync completes successfully, no errors, no warnings.

### Additional details:
- macOS 10.12.4
- Bazel 0.4.5
- IntelliJ IDEA Ultimate 2017.1.2
- IJWB 2017.04.17.6

**Comment by philwo** [comment]
@dslomov FYI

**Comment by brendandouglas** [comment]
The changes we made to our aspect to support `java_proto_library` didn't make it into Bazel 0.4.5. If you build Bazel from HEAD this should resolve correctly.

Also see https://github.com/bazelbuild/intellij/issues/75

As an aside, I just noticed that https://github.com/bazelbuild/bazel/issues/1820 is fixed, which is very exciting. I believe that will allow us to package our aspect with the plugin, rather than bundling it with Bazel (a long-standing goal of ours). In the future, that will mean changes such as this one can be rolled out with our plugin, rather than being tied to Bazel releases.
