### ISSUE TITLE
Bazel plugin does not recognize workspace mappings in debug run

### ISSUE THREAD

**Issue by karamach** [bazelbuild/intellij#94]
I have a bazel project where some external directories are mapped to the sandbox in the WORKSPACE file. When running a test configuration , it is able to locate the external files fine but when I run it as Debug , it is not able to locate the same files.

**Comment by brendandouglas** [comment]
Do you have an example project that demonstrates this?

I'll try and reproduce, but might need a bit more information:
- what language is the test in?
- what kind of workspace rule is it (e.g. maven_jar, git_repository, etc.)?
- how does the problem manifest? (e.g. does it navigate to decompiled code when debugging, rather than the source code, does the test fail completely)

Thanks!

**Comment by brendandouglas** [comment]
Closing for bug hygiene reasons. Please reopen with details if this is still happening -- thanks!
