### ISSUE TITLE
Running tests in directory fails to find tests due to invalid target (:all)

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#957]
It seems that a recent refactoring (#866) caused a change in the `AllInPackage` run config that now calls the non-recursive `TargetExpression.allFromPackageNonRecursive(packagePath)` method to calculate the target.

Previously, the code would call the recursive one, and the target produced would be e.g. `//my-target/...:all`, which did the right thing by running all sub-targets, but now the produced target is `//my-target:all`, which causes the test runner not to find any tests.

Was this done on purpose? Or is it a bug?

@brendandouglas

**Comment by ittaiz** [comment]
@brendandouglas was it done on purpose?

**Comment by brendandouglas** [comment]
Sorry for the delay replying. This was an intentional change, to avoid kicking off very expensive builds in cases where there are a lot of nested bazel packages.

It shouldn't be an invalid target though, as it first checks if the directory is a bazel package. Perhaps it fails for empty bazel packages, or the code has misclassified a directory as a bazel package?

**Comment by ittaiz** [comment]
First sorry for a very late reply :)
I think the mismatch is that we have many packages which have filegroups due to cycles.
Additionally for people this was a significant feature for us since it was a way for people to run all tests of an area intentionally.

I know you're wary of configuration options but I feel that here, as in a few other discussions we had, the opinionated choice can be debatable and completely doesn't suit our needs.
It would be really useful for us to be able to toggle this off for our users.

Btw, you might, legitimately, ask yourself why we haven't done anything about it since it was broken and the honest answer is that we've been focused on a few more fundamental issues like people having red code constantly. 

Would love to hear your thoughts,
Ittai

**Comment by ittaiz** [comment]
We ended up implementing this in our plugin as a `TestContextProvider`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by ittaiz** [comment]
@sgowroji one general question- why are you closing the issues as completed? Can you close them as won't fix? 
This at least communicates in a structured way (labels) they didn't happen.
I think you should do it for all of the tens of issues you recently closed

**Comment by sgowroji** [comment]
Thanks for the input i will consider and update those.
